APP:
  SEED: 1
CORES_AVAILABLE: <INTEGER> # number of cores to parallel workflow step execution
CURRENT_SET: <> # does not need to be set, will be constructed during the analysis
EXPERIMENT_NAME: <> # does not need to be set, will be constructed during the analysis
INCLUDE_SIMULATION_PIPELINE: true # toggle to false if simulation should be skipped and user provided (real) data should be used
POSTPRED:
  LABELS: # key value pairs, matching names to the unique ID of each simulated, independent DATASET; IDs are used in the subsequent instruction how the time course should be simulated (see SIMULATION -> DATASET -> NAME)
  - key: <CHARACTER>
    value: <CHARACTER>
  LINEAGE_MIN_THRESHOLD: <FLOAT> # minimal relative abundance in [0,1] for a lineage to be considered
  MIN_READ_COUNT: <INTEGER> # minimal read count per position to be considered for mutation calling
REFERENCES:
  PRIMER_SET:  <CHARACTER> # relative path to the primer scheme description in bed4 file format 
  REF_GENOME: <CHARACTER> # relative path to the virus reference file in fasta file format 
  REF_HUMAN: <CHARACTER> # relative path to the genomic background file in fasta file format 
SIMULATION:
  AMPLICON_DISTRIBUTION:  <CHARACTER> # method passed on to SWAMPy's *amplicon_distribution* option. Currently only <dirichlet_1> is a valid value. See SWAMPy documentation for details.
  AMPLICON_PSEUDOCOUNTS: <INT> # method passed on to SWAMPy's *amplicon_pseudocounts* option. Currently only <dirichlet_1> is a valid value. See SWAMPy documentation for details.
  DATASET: # description of difference DATASETS and how they are simulated
    SET_01: # generic name, stick to nomenclature SET_{01,02,03,..}
      CONSTANT_VARIANT_ABUNDANCE: <FLOAT> # relative abundance of a constantly simulated background variant, e.g. the WT strain. Need to be in [0,1[
      EXPERIMENT_NO_START: <INTEGER> # start index of different experiments within the DATASET, typically <1>
      FORM_PARA: 
        growth_rate: <FLOAT> # growth rate used to simulate the underlying case dynamic, typical value is <0.02>
        init_cases: <INTEGER> # intial numbers of cases; used to simulate the underlying case dynamic, typical value is <1>
        max_cases: <INTEGER> # maximal numbers of cases; used to simulate the underlying case dynamic, typical value is <1000000>
      MAX_TIMEPOINTS: <INTEGER> # numbers of timepoints to be simulated for one DATASET; used to simulate the underlying case dynamic, typical value is <365>
      NAME: <CHARACTER> # ID of DATESET, should be unique and no spaces allowed. Can be used in POSTPRED->POSTPRED to be associated with a more telling name
      START_DATE: <YYYY-MM-DD> # date of first timepoints to be simulated for one DATASET; used to simulate the underlying case dynamic, typical value is <2023-01-01>
      USE_REAL_TIMECOURSE: false # toggle to true if underlying timecourse should not be simulated but variant frequencies are externally provided
      TIMECOURSE_DATA: <CHARACTER> # if USE_REAL_TIMECOURSE == true, provide path to variant abundance file in the following format: <sample_date>	<lineage>	<totalCases>	<lineageCases>	<relativeAbundance>	<Location>
      VARIANTS: # definition of variants to simulate DATASET
        variant_1: # consecutive name of variant (variant_n)
        - <INTEGER>        # start of exponential growth, e.g. 1
        - <CHARACTER>  # name of the variant, should corespond to REFERENCES_SEQUENCES fasta file, e.g. B.1.1.7
  N_READS: <INTEGER> # number of simulated reads
  N_SEED: <INTEGER> # seed used for the read simulation
  PRIMER_SET: <CHARACTER> # name of the primer set used
  QUALITY_SCORES:
  - <INTEGER> # list of values of different quality score, passed on to SWAMPy's . typical value [1,400] with higher values producing better genome coverage
  - <INTEGER> # continue list from above if needed
  READ_LENGTH: <INTEGER> # read length, typical value <250>
  REFERENCES_SEQUENCES:  # reference sequence in fasta file format for different lineages used in the simulation.
  - <CHARACTER> # path to fasta file
  - <CHARACTER> # path to fasta file
  SAMPLE_COLLECTION:
    NUMBER: <INTERGER> # number of sample drawn from the underlying simulated timecourse
    SAMPLE_MODE: <CHARACTER> # specifies how samples should be drawn from time course. accepted values are "all", "even" or "random"
  SEQ_SYS: <CHARACTER> # passed on to SWAMPy to specify applied error model. typical value <MSv3>
TOOLS: # list of tools to be applied
  TOOL_01: 
    COLOUR_IN_REPORT: <CHARACTER> # Color in HEX used in the plots of the report
    DESCRIPTION: <CHARACTER> # free text to describe tool or version, passed on to the report
    INCLUDE_IN_ANALYSIS: <BOOLEAN> # toggle to false if tool should be omitted
    TOOL_LABEL: <CHARACTER> # name of the tool used in the report
    TOOL_NAME: <CHARACTER> # ID of the tool, should be unique
  TOOL_N:
    COLOUR_IN_REPORT: '#5D8CA8FF'
    DESCRIPTION: current github version
    INCLUDE_IN_ANALYSIS: true
    TOOL_LABEL: VaQuERo v24d9211
    TOOL_NAME: vaquero_v24d9211
